### ISSUE TITLE
dubbo单点zk在短时间不可用时,会反复请求ZK直到把机器连接数打满

### ISSUE THREAD

**Issue by yinggaozhen** [dubbo/dubbo2.js#71]
- 操作系统 : Centos7.2
- Node : 8.5.0
- Dubbo2.js : 2.3.5

你好,我的测试dubbo zk是单点的,在zk短时间不可用时,会可能出现反复的大量不重复请求zk 2181端口,并且都建立成功(直到把单机连接数打满或者buffer index out of range).
看了一下代码,重新建立连接只会在zookeeper.ts里的expired会出现.
请问还有什么情况下会出现服务器把反复与zk建立连接,且都建立成功,直到达到单机连接数打满的情况?      

目前已经发版多次,此类问题在灰度期间经过一段时间之后必现.
另外,ZK如果改为集群的话,是否会有所改善?

日志如下:
```
{ time: '2018-12-06T15:45:24.371Z',
  pid: 9999,
  host: '1.1.1.1',
  type: 'ERR',
  msg:
   Error: ZooKeeper was disconnected. current state is DISCONNECTED[0]
       at Client._client.on (/test/node_modules/dubbo2.js/es7/zookeeper.js:112:26)
       at emitNone (events.js:105:13)
       at Client.emit (events.js:207:7)
       at Client.defaultStateListener (/test/node_modules/node-zookeeper-client/index.js:52:14)
       at emitOne (events.js:115:13)
       at Client.emit (events.js:210:7)
       at Client.onConnectionManagerState (/test/node_modules/node-zookeeper-client/index.js:262:14) }
{ time: '2018-12-06T15:45:24.389Z',
  pid: 9999,
  host: '1.1.1.1',
  type: 'ERR',
  msg:
   Error: Zookeeper was session Expired Error current state EXPIRED[-122]
       at Client._client.on (/test/node_modules/dubbo2.js/es7/zookeeper.js:116:26)
       at emitNone (events.js:105:13)
       at Client.emit (events.js:207:7)
       at Client.defaultStateListener (/test/node_modules/node-zookeeper-client/index.js:61:14)
       at emitOne (events.js:115:13)
       at Client.emit (events.js:210:7)
       at Client.onConnectionManagerState (/test/node_modules/node-zookeeper-client/index.js:262:14) }

{ time: '2018-12-06T15:45:24.371Z',
  pid: 9999,
  host: '1.1.1.1',
  type: 'ERR',
  msg:
   Error: ZooKeeper was disconnected. current state is DISCONNECTED[0]
       at Client._client.on (/test/node_modules/dubbo2.js/es7/zookeeper.js:112:26)
       at emitNone (events.js:105:13)
       at Client.emit (events.js:207:7)
       at Client.defaultStateListener (/test/node_modules/node-zookeeper-client/index.js:52:14)
       at emitOne (events.js:115:13)
       at Client.emit (events.js:210:7)
       at Client.onConnectionManagerState (/test/node_modules/node-zookeeper-client/index.js:262:14) }
{ time: '2018-12-06T15:45:24.389Z',
  pid: 9999,
  host: '1.1.1.1',
  type: 'ERR',
  msg:
   Error: Zookeeper was session Expired Error current state EXPIRED[-122]
       at Client._client.on (/test/node_modules/dubbo2.js/es7/zookeeper.js:116:26)
       at emitNone (events.js:105:13)
       at Client.emit (events.js:207:7)
       at Client.defaultStateListener (/test/node_modules/node-zookeeper-client/index.js:61:14)
       at emitOne (events.js:115:13)
       at Client.emit (events.js:210:7)
       at Client.onConnectionManagerState (/test/node_modules/node-zookeeper-client/index.js:262:14) 
```

**Comment by hufeng** [comment]
@yinggaozhen 谢谢你，我review下代码，是有这个问题 https://github.com/dubbo/dubbo2.js/commit/e1a2f9258bceb216de0b6152af06be979b797201 这个地方处理的有问题
在这个版本https://github.com/dubbo/dubbo2.js/commit/0afa064cde5806fc93289143d1df3c0a83185029
fixed了
最新的代码里面感觉merge的代码有问题 又合入了
我来fix下 非常感谢。

**Comment by yinggaozhen** [comment]
赞!

**Comment by hufeng** [comment]
@yinggaozhen 升级到2.3.6试试
