### ISSUE TITLE
sokcetWorker在尝试重试第一次后,Socket会与provider反复尝试建立连接,最终导致内存溢出

### ISSUE THREAD

**Issue by yinggaozhen** [dubbo/dubbo2.js#79]
- 操作系统 : Centos7.2
- Node : 8.5.0
- Dubbo2.js : 2.3.6
- pm2 : 2.8.0

在特定情况(譬如每次压测之后,每次压测会伴随着很多大批量provider同时注册/摘除),部分socket在尝试重试连接之后,会在retry第一次之后,便不再尝试连接(可能已经连接成功,但是根据正常重连的情况来看,通常要重试多次才会正常连接,重试第一次就成功感觉有点异常),但是此时socket会反复与provider尝试建立连接,发起连接之后便断开,然后反复发起连接/断开,造成了机器的内存溢出.
provider服务正常,也已排除因provider连接数限制的情况.

相关日志 :
**Node日志**
```
3|node-com |    Error: SocketWorker#6 <=closed=> 1.1.1.1:20880 hadError: false retry: 20
3|node-com |        at SocketWorker._onClose (/test/node_modules/dubbo2.js/es7/socket-worker.js:76:29) }
3|node-com | { time: '2019-01-08T23:35:46.707Z',
3|node-com |   pid: 20684,
3|node-com |   host: '10.1.1.1',
3|node-com |   type: 'ERR',
3|node-com |   msg: 
3|node-com |    Error: SocketWorker#43 <=closed=> 1.1.1.2:20880 hadError: false retry: 20
3|node-com |        at SocketWorker._onClose (/test/node_modules/dubbo2.js/es7/socket-worker.js:76:29) }
3|node-com | { time: '2019-01-08T23:35:46.707Z',
3|node-com |   pid: 20684,
3|node-com |   host: '10.1.1.1',
3|node-com |   type: 'ERR',
3|node-com |   msg: 
3|node-com |    Error: SocketWorker#12 <=closed=> 1.1.1.3:20880 hadError: false retry: 20
3|node-com |        at SocketWorker._onClose (/test/node_modules/dubbo2.js/es7/socket-worker.js:76:29) }
3|node-com | { time: '2019-01-08T23:37:51.553Z',
3|node-com |   pid: 20684,
3|node-com |   host: '10.1.1.1',
3|node-com |   type: 'ERR',
3|node-com |   msg: 
3|node-com |    Error: SocketWorker#26 <=closed=> 1.1.1.4:20880 hadError: false retry: 20
3|node-com |        at SocketWorker._onClose (/test/node_modules/dubbo2.js/es7/socket-worker.js:76:29) }
```

**socket与provider建立连接情况**
出现了大量异常的ESTABLISHED/CLOSE_WAIT,正常建立连接之后是不存在CLOSE_WAIT

```
tcp       52      0 10.1.1.1:12612      1.1.1.12:20880      CLOSE_WAIT  20684/node /test
tcp       35      0 10.1.1.1:26119      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:57477      1.1.1.14:20880      CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:8208       1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:30924      1.1.1.18:20880      CLOSE_WAIT  20684/node /test
tcp       35      0 10.1.1.1:6522       1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:33476      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       35      0 10.1.1.1:57727      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:58981      1.1.1.12:20880      CLOSE_WAIT  20684/node /test
tcp        0      0 10.1.1.1:28434      1.1.1.1:7000        ESTABLISHED 20684/node /test
tcp       35      0 10.1.1.1:49164      1.1.1.17:20880      CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:9532       1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       35      0 10.1.1.1:48187      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:3229       1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp        0      0 10.1.1.1:35650      1.1.1.1:3306        ESTABLISHED 20684/node /test
tcp       18      0 10.1.1.1:1957       1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:1296       1.1.1.15:20880      CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:26638      1.1.1.19:20880      CLOSE_WAIT  20684/node /test
tcp       35      0 10.1.1.1:12799      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:27273      1.1.1.12:20880      CLOSE_WAIT  20684/node /test
tcp        8      0 10.1.1.1:22999      1.1.1.1:7000        ESTABLISHED 20684/node /test
tcp       18      0 10.1.1.1:29326      1.1.1.18:20880      CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:23916      1.1.1.10:20880      CLOSE_WAIT  20684/node /test
tcp       18      0 10.1.1.1:14173      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:48416      1.1.1.17:20880      CLOSE_WAIT  20684/node /test
tcp       18      0 10.1.1.1:34663      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       18      0 10.1.1.1:41749      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       82      0 10.1.1.1:22884      1.1.1.1:7000        ESTABLISHED 20684/node /test
tcp       35      0 10.1.1.1:64487      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp        0      0 10.1.1.1:52153      1.1.1.1:3306        ESTABLISHED 20684/node /test
tcp       35      0 10.1.1.1:40382      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:57110      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:21707      1.1.1.11:20880      CLOSE_WAIT  20684/node /test
tcp       18      0 10.1.1.1:45241      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       35      0 10.1.1.1:41369      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       18      0 10.1.1.1:4075       1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp       52      0 10.1.1.1:28700      1.1.1.1:20880       CLOSE_WAIT  20684/node /test
tcp        0      0 10.1.1.1:32298      1.1.1.1:7000        ESTABLISHED 20684/node /test
```

**pm2情况**
其中,进程3出现内存溢出问题
```
┌────────────────────────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬────────────┬──────┬──────────┐
│ App name                       │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem        │ user │ watching │
├────────────────────────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼────────────┼──────┼──────────┤
│ node-service │ 0  │ cluster │ 20661 │ online │ 18      │ 5D     │ 0%  │ 108.7 MB   │ root │ disabled │
│ node-service │ 1  │ cluster │ 2446  │ online │ 19      │ 9h     │ 0%  │ 120.4 MB   │ root │ disabled │
│ node-service │ 2  │ cluster │ 20683 │ online │ 18      │ 5D     │ 0%  │ 112.9 MB   │ root │ disabled │
│ node-service │ 3  │ cluster │ 20684 │ online │ 18      │ 5D     │ 0%  │ 2.8 GB     │ root │ disabled │
```

**Comment by hufeng** [comment]
@yinggaozhen  请问使用的哪个版本

**Comment by yinggaozhen** [comment]
2.3.6
