### ISSUE TITLE
examples/hello-koa里的es6-http执行报错呢~

### ISSUE THREAD

**Issue by wu666lei** [dubbo/dubbo2.js#85]
Error: uuid:  invoke cn.jsfund.cps.query.TestService#testQuery was error, requestId#1:Could not find any agent worker with cn.jsfund.cps.query.TestService#1.0.0# agentList: 
    at Scheduler._handleDubboInvoke (/Users/xujine/WebstormProjects/gitWorkspace/dubbo2/examples/hello-koa/node_modules/dubbo2.js/es7/scheduler.js:173:25)
    at Queue.Scheduler._handleQueueRequest.requestId [as _subscriber] (/Users/xujine/WebstormProjects/gitWorkspace/dubbo2/examples/hello-koa/node_modules/dubbo2.js/es7/scheduler.js:47:26)
    at Promise (/Users/xujine/WebstormProjects/gitWorkspace/dubbo2/examples/hello-koa/node_modules/dubbo2.js/es7/queue.js:57:22)
    at new Promise (<anonymous>)
    at Queue.add (/Users/xujine/WebstormProjects/gitWorkspace/dubbo2/examples/hello-koa/node_modules/dubbo2.js/es7/queue.js:39:20)
    at handleRequest (/Users/xujine/WebstormProjects/gitWorkspace/dubbo2/examples/hello-koa/node_modules/dubbo2.js/es7/dubbo.js:88:66)
    at dispatch (/Users/xujine/WebstormProjects/gitWorkspace/dubbo2/examples/hello-koa/node_modules/dubbo2.js/node_modules/koa-compose/index.js:42:32)
    at /Users/xujine/WebstormProjects/gitWorkspace/dubbo2/examples/hello-koa/node_modules/dubbo2.js/node_modules/koa-compose/index.js:34:12
    at Object.proxyObj.(anonymous function) [as testQuery] (/Users/xujine/WebstormProjects/gitWorkspace/dubbo2/examples/hello-koa/node_modules/dubbo2.js/es7/dubbo.js:95:31)
    at Server.http.createServer (/Users/xujine/WebstormProjects/gitWorkspace/dubbo2/examples/hello-koa/es6-http.js:6:32)

**Comment by hufeng** [comment]
hi @wu666lei , example实例只能调用注册到dubbo对象service中的服务

**Comment by wu666lei** [comment]
您好，您看我这边service改的有问题么？为什么调用不到呢，惆怅
provider.TestService = dubbo =>
  dubbo.proxyService({
    dubboInterface: 'cn.jsfund.cps.query.TestService',
    methods: {
      testQuery(paramter){
        return [
          java.combine('cn.jsfund.cps.query.TestParameter', paramter),
        ];
        //return [java('cn.jsfund.cps.query.TestParameter',paramter)];
      },
      // sayHello(name) {
      //   return [java.String(name)];
      // },

      // echo() {},
      //
      // test() {},
      //
      // getUserInfo() {
      //   return [
      //     java.combine('com.alibaba.dubbo.demo.UserRequest', {
      //       id: 1,
      //       name: 'nodejs',
      //       email: 'node@qianmi.com',
      //     }),
      //   ];
      // },
    },
  });

const app = http.createServer((req, response) => {
  if (req.url === '/dubbo') {
    dubbo.service.TestService.testQuery({ id: '1', name: '3' }).then(({res, err}) => {
      console.log('res',res,err);
      response.end(res);
    });
  }
});

**Comment by hufeng** [comment]
@wu666lei 看起来是对的，这样你创建一个小demo在你的仓库，我来跑下 帮你看下

**Comment by wu666lei** [comment]
@hufeng 通过查找源码报错，找到原因了。原来是严格要求version配置与provider的一致，之前用别的包调试好像没这个限制~,😁   多谢耐心回复
this._dubboServiceUrlMap
            .get(dubboInterface)
            .filter(serviceProp => {
            const isSameVersion = serviceProp.version === version;
            //如果Group为null，就默认匹配， 不检查group
            //如果Group不为null，确保group和接口的group一致
            const isSameGroup = !group || group === serviceProp.group;
            return isSameGroup && isSameVersion;

**Comment by hufeng** [comment]
@wu666lei group和version 还是要严格的 不然就是调通了也不一定是调用正确 😃

P.S 有默认值 
![image](https://user-images.githubusercontent.com/533008/54504676-85699f00-496f-11e9-8b50-f088e8f83da7.png)

祝玩的愉快😃，有问题沟通。
