### ISSUE TITLE
sayHello not all arguments are valid hessian type

### ISSUE THREAD

**Issue by sunchuanleihit** [dubbo/dubbo2.js#93]
(async () => {
  const result1 = await dubbo.service.DemoProvider.sayHello('node');
  console.log(result1);

  const result2 = await dubbo.service.DemoProvider.echo();
  console.log(result2)
})();

DemoProvider#sayHello not all arguments are valid hessian type
       at Function._checkMethodArgsHessianType (/Users/sunchuanlei/dubbojs/node_modules/dubbo2.js/es7/queue.js:179:20)
       at Promise (/Users/sunchuanlei/dubbojs/node_modules/dubbo2.js/es7/queue.js:43:28)
       at new Promise (<anonymous>)
       at Queue.add (/Users/sunchuanlei/dubbojs/node_modules/dubbo2.js/es7/queue.js:39:20)
       at handleRequest (/Users/sunchuanlei/dubbojs/node_modules/dubbo2.js/es7/dubbo.js:88:66)
       at dispatch (/Users/sunchuanlei/dubbojs/node_modules/koa-compose/index.js:42:32)
       at next (/Users/sunchuanlei/dubbojs/node_modules/koa-compose/index.js:43:18)
       at Object.<anonymous> (/Users/sunchuanlei/dubbojs/test.ts:20:9)
       at step (/Users/sunchuanlei/dubbojs/test.ts:32:23)
       at Object.next (/Users/sunchuanlei/dubbojs/test.ts:13:53) }

这个是什么问题

**Comment by hufeng** [comment]
@sunchuanleihit 为了避免runtime的类型问题，所有的参数 都要使用hassian的格式
 可以使用js-to-java这个语法糖模块

```javascript
const {java} = require('dubbo2.js');
const result1 = await dubbo.service.DemoProvider.sayHello(java.String('node'));
```
